version: '3.3'

services:
  aspnetapp:
    image: aspnetapp
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on: 
      - db
    ports: 
      - "8080:80"
  db:
    image: "microsoft/mssql-server-linux:latest"
    container_name: db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA:  "Y"
      SA_PASSWORD:  "DemoPassword.1"
      MSSQL_PID: "Developer"